AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'python3.10

  Sample SAM Template for lab-api

  '
Globals:
  Function:
    Timeout: 300
  Api:
    Cors:
      AllowMethods: '''GET,POST,OPTIONS'''
      AllowHeaders: '''content-type'''
      AllowOrigin: '''*'''
Parameters:
  SourceBucketName:
    Type: String
    Default: tracks-source-nl
  DestinationBucketName:
    Type: String
    Default: tracks-destination-nl
Resources:
  SourceAudio:
    Type: AWS::S3::Bucket
    Properties:
      BucketName:
        Ref: SourceBucketName
  DestinationAudio:
    Type: AWS::S3::Bucket
    Properties:
      BucketName:
        Ref: DestinationBucketName
  CreateStems:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Architectures:
      - x86_64
      Policies:
      - S3ReadPolicy:
          BucketName:
            Ref: SourceBucketName
      - S3CrudPolicy:
          BucketName:
            Ref: DestinationBucketName
      Environment:
        Variables:
          DESTINATION_BUCKET:
            Ref: DestinationBucketName
          SOURCE_BUCKET:
            Ref: SourceBucketName
      Events:
        CreateStems:
          Type: Api
          Properties:
            Path: /split
            Method: post
        FileUpload:
          Type: S3
          Properties:
            Bucket:
              Ref: SourceAudio
            Events: s3:ObjectCreated:*
      ImageUri: createstems:python3.10
    Metadata:
      DockerContext: /Users/senyo/Desktop/NOISELAB/lapi/src/split
      DockerTag: python3.10
      Dockerfile: Dockerfile
      SamResourceId: CreateStems
Outputs:
  CreateStemsApi:
    Description: API Gateway endpoint URL for Prod stage for Hello World function
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/split/
